INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (1, '广船国际有限公司党委副书记张庆环一行来校考察-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1021/17016.htm', '1766');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (2, '[《江南都市报》报道] 九江职业技术学院联合多部门开展校园及周边治安环境综合整治行动-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1028/16738.htm', '476');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (3, '[《江南都市报》报道] 九江职业技术学院召开2022届毕业生就业创业工作推进会-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1028/16938.htm', '447');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (4, '[《江南都市报》报道] 九江职业技术学院教师喜获佳绩——2021年江西省学校共青团“微团课”大赛圆满结束-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1028/16565.htm', '627');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (5, '九江职业技术学院学生勤工助学管理实施细则-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1027/11756.htm', '1600');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (6, '江西省学生资助工作“十不准”（修订版）-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1027/11774.htm', '1523');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (7, '[《江南都市报》报道] 九江职业技术学院开展“用青春护绿水‘河小青’在行动”志愿服务-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1028/16937.htm', '510');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (8, '九江职业技术学院家庭经济困难学生认定工作实施办法（2019年修订）-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1027/12378.htm', '4292');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (9, '[《江西日报》报道] 九江职业技术学院坚决打赢疫情防控攻坚战-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1028/16737.htm', '603');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (10, '[《江西日报》报道] 精准化指导  高质量就业  九江职业技术学院让高职生大有可为-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1028/16503.htm', '713');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (11, '[《江西日报》报道] 九江职业技术学院在党史学习教育中开新局-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1028/16566.htm', '586');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (12, '建筑工程学院开展“以我之笔，‘井’上添花”井盖涂鸦活动-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1022/17086.htm', '160');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (13, '文化扬正气，诗词润人心——电气工程学院开展传统文化趣味竞赛活动-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1022/17089.htm', '130');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (14, '汽车工程学院开展“做一颗闪亮的星”劳动教育主题讲座-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1022/17087.htm', '131');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (15, '经济管理学院开展预防电信网络诈骗系列教育活动-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1022/17079.htm', '175');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (16, '我校学子在“2021一带一路暨金砖国家技能发展与技术创新大赛”中喜获佳绩-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1113/16418.htm', '1162');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (17, '九江职业技术学院关于公布2018年度信息化教学比赛结果的通知-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1025/10178.htm', '4260');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (18, '关于开展2020届毕业生培养质量评价的通知-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1025/14746.htm', '2965');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (19, '濂溪区2021年“世界艾滋病日”主题宣传活动在我校举行-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1113/16404.htm', '1205');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (20, '关于开展2019届毕业生培养质量评价的通知-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1025/13150.htm', '2546');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (21, '我校举办第三届“党在心田 宪法伴行”诗歌朗诵会-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1113/16403.htm', '1206');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (22, '我校组织开展“12.5国际志愿者日”系列志愿服务活动-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1113/16402.htm', '1446');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (23, '关于开展2021届毕业生培养质量评价的通知-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1025/16526.htm', '1223');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (24, '九江职业技术学院VR资源开发中心采购项目(采购编号：HWZC2223)竞争性磋商采购公告-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1061/17061.htm', '174');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (25, '我校参加全省提质培优行动计划1+X制度试点工作推进会-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1112/16833.htm', '1044');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (26, '九江职业技术学院濂溪校区大学生活动中心及学生公寓工程预算编制咨询服务项目(采购编号：HWZC2231）比选招标采购成交结果公告-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1061/17060.htm', '148');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (27, '九江职业技术学院核酸检测服务采购项目(采购编号：HWZC2237)终止公告-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1061/17081.htm', '91');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (28, '微服务助力疫情防控，信息化赋能管理增效-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1112/16799.htm', '576');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (29, '我校召开2022年省教师教学能力比赛工作推进会-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1112/16950.htm', '1357');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (30, '我校参加金砖国家职业教育联盟大会-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1112/16983.htm', '1360');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (31, '我校举办2022“规划未来，梦圆九职”大学生职业生涯规划大赛-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1021/17091.htm', '920');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (32, '我校举办2022劳动教育宣传月“劳模进校园”主题讲座-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1021/17090.htm', '722');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (33, '我校组织开展江西省第十六届运动会志愿者通用培训-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1021/17062.htm', '1076');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (34, '我校举行“九职之星”大学生骨干培训班第十五期结业暨第十六期开班仪式-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1021/17063.htm', '798');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (35, '图解③｜九江职业技术学院“十四五”发展蓝图！（学生篇）-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1021/17093.htm', '2175');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (36, '我校举行第二十届“5·25”大学生心理健康教育宣传月开幕式暨心理游园活动-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1021/17094.htm', '592');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (37, '学校党委理论学习中心组开展“数字经济”专题学习研讨-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1021/17008.htm', '1301');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (38, '我校召开疫情防控工作部署会-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1021/16796.htm', '1516');
INSERT INTO `jvtc_data` (`id`, `name`, `url`, `hits`) VALUES (39, '我校召开2022年“五四”表彰大会-九江职业技术学院', 'https://www.jvtc.jx.cn/info/1021/16948.htm', '2484');
